name: CI/CD - Development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install project dependencies
      - name: Install Dependencies
        run: npm install


      # 5. Build the application (development mode)
      - name: Build Application (Development)
        run: npm run build

