name: CI/CD - Development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'


      - name: Install Dependencies
        run: npm install


      - name: Build Application (Development)
        run: ng build

      - name: Deploy to GitHub Pages (Development)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/blooming-ui
